name: Test2
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-action:
    name: Run action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: UnitTests/api/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: UnitTests/api

      - name: Test
        run: npm run test
        working-directory: UnitTests/api

      - name: Build
        run: npm run build
        working-directory: UnitTests/api